### ISSUE TITLE
View for Alfresco mobile app

### ISSUE THREAD

**Issue by jclandron** [atolcd/alfresco-audit-share#12]
Hello, 

Can you tell me a view exist for audit-share we can add in Afresco mobile app ?

Thanks, 
Regards,
jcland

**Comment by bforest** [comment]
Hello,

Sorry, there is no AuditShare add-in for the Afresco mobile app.

Regards.

**Comment by jclandron** [comment]
Hello, 

Thanks for your reply.

Regards
