### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by monicakumari** [atolcd/alfresco-audit-share#13]
hello,
I am not able to build this ant project. I am working on latest sdk/alfresco 201707. I have tried  **ant prepare-package-amp** to build the project but getting the following errors :
[error-logs.txt](https://github.com/atolcd/alfresco-audit-share/files/1814342/error-logs.txt)

I don't understand the meaning of "Before building, ensure you have edited the build.properties files to set the path to your Alfresco SDK" line.
I mean, about the path. what could be the path to set in build.properties file ? 
may you please guide me about this ? 
Also, I wanted to know how iBATIS is working here ?

Thanks.

**Comment by bforest** [comment]
Hi,

GitHub sources have been updated.
Now please use Maven to compile sources : mvn clean package

Regards.
