### ISSUE TITLE
Request to get most viewed documents API

### ISSUE THREAD

**Issue by SandeepReddy496** [atolcd/alfresco-audit-share#15]
Hi Sir,

can you please suggest me, i need most viewed documents API from this project.

**Comment by bforest** [comment]
Hi,

You can do this using this URL:
http://server:port/alfresco/s/share-stats/select-audits?type=mostread&module=document&sites=*&limit=1000

You can change parameters for filtering results:
 - sites: coma separated site ids
 - limit: max results
 - from: timestamp (eg: 1514761200000)
 - to: timestamp (eg: 1546297200000)


Regards.

**Comment by SandeepReddy496** [comment]
Hi bforest,
Thank you soo much sir,
I request you, Can you please suggest me most worked month in the year, and Most liked documents.

**Comment by bforest** [comment]
Hi,

AuditShare doesn't have information about liked documents, sorry.

It depends what mean "most worked month" but you probably have to agregate "counts" of:
 - readings
http://server:port/alfresco/s/share-stats/select-audits?type=read&dates=1514761200000,1517439600000,1519858800000,1522533600000,1525125600000,1527804000000,1530396000000,1533074400000,1535752800000,1538344800000,1541026800000,1543618800000,1546297200000&module=document&sites=*
 - updates
http://server:port/alfresco/s/share-stats/select-audits?type=updated&dates=1514761200000,1517439600000,1519858800000,1522533600000,1525125600000,1527804000000,1530396000000,1533074400000,1535752800000,1538344800000,1541026800000,1543618800000,1546297200000&module=document&sites=*
 - creations
http://server:port/alfresco/s/share-stats/select-audits?type=created&dates=1514761200000,1517439600000,1519858800000,1522533600000,1525125600000,1527804000000,1530396000000,1533074400000,1535752800000,1538344800000,1541026800000,1543618800000,1546297200000&module=document&sites=*


Regards.
