### ISSUE TITLE
not an issue, just a kind of enhancement

### ISSUE THREAD

**Issue by monicakumari** [atolcd/alfresco-audit-share#17]
Hello, 
Thank you for this updated code. I have tried it and I like it. It is showing the data from the day it is applied to an instance. I wanted know, Is there any way I can see the old data too ? 
like, I have applied its amps today to an instance and It's showing today's data. Is there any way, It can fetch the yesterday's data and day before yesterday. 

Thanks.

**Comment by bforest** [comment]
Hello,

Data are stored in AuditShare tables only from installation date of the module.

Regards.
