### ISSUE TITLE
I need Help for most viewed documents every 15 days

### ISSUE THREAD

**Issue by SandeepReddy496** [atolcd/alfresco-audit-share#19]
Hi Sir,
I need to show most viewed documents for  Every 15 days.
Can you please suggest me,

and is it possible to show most viewed documents from particular group people in alfresco ..?

i need help sir

**Comment by bforest** [comment]
Hi,

I've already explain how to get most viewed documents on issue #15 (https://github.com/atolcd/alfresco-audit-share/issues/15).


You can do this using this URL:
http://server:port/alfresco/s/share-stats/select-audits?type=mostread&module=document&sites=*&limit=1000

You can change parameters for filtering results:

- sites: coma separated site ids
- limit: max results
- from: timestamp (eg: 1514761200000)
- to: timestamp (eg: 1546297200000)
    
For example for the past 15 days:
http://server:port/alfresco/s/share-stats/select-audits?type=mostread&module=document&sites=*&limit=1000&from=1522491061944&to=1523787061944

It's not possible to filter results by group membership on "select-audits" webscript but it's a good idea, it could be an enhancement.

Regards.

**Comment by SandeepReddy496** [comment]
Hi Sir,
Thank you soo much for the reply sir.,
http://localhost:8080/alfresco/s/share-stats/select-audits?type=mostread&module=document&sites=mysite&limit=1000

here i mentioned
sites= mysite but it is showing error.

i need to show single site most read documents with usernames. can you please suggest me sir

**Comment by SandeepReddy496** [comment]
Hi Sir,
I want to search videos and documents(all items) in a site.
which API i need to use sir ...?

**Comment by bforest** [comment]
Hi,

It's not possible to do that with AuditShare.

Regards.

**Comment by bforest** [comment]
About the error "SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data".
You need to be administrator or site manager of the site "mysite" to be able to retrieve AuditShare data.

Regards.

**Comment by SandeepReddy496** [comment]
Ok Sir,
Thank you soo much for the reply,

can i see which users read the documents ...?

when i hitting the API  http://localhost:8080/alfresco/s/share-stats/select-audits?type=mostread&module=document&sites=bsg&limit=1000

i am getting following data, but i need to show which users read the documents instead of 
popularity	3.
i mean popularity	3(three read popularity with three usernames)

i need your help for this sir.

items	
0	
popularity	3
nodeRef	"workspace://SpacesStore/ef7e09c2-0c3f-4378-9bf7-da61f19422f1"
site	"bsg"
siteTitle	"BSG"
siteComponent	"documentLibrary"
name	"Health Check Document.docx"
displayName	"Health Check Document.docx"
1	
popularity	2
nodeRef	"workspace://SpacesStore/79a5eaf8-a262-4397-8f99-17888a497907"
site	"bsg"
siteTitle	"BSG"
siteComponent	"documentLibrary"
name	"Testing.txt"
displayName	"Testing.txt"
2	
popularity	2
nodeRef	"workspace://SpacesStore/fa358da5-1d2b-4893-9608-da26b9dcf08c"
site	"bsg"
siteTitle	"BSG"
siteComponent	"documentLibrary"
name	"HealthCheck5.png"
displayName	"HealthCheck5.png"

**Comment by bforest** [comment]
No, "select-audits" doesn't return which users read the documents.

Regards.

**Comment by SandeepReddy496** [comment]
Hi sir,

Is it possible to give the permission to SiteCollaborator and SiteContributor to retrieve AuditShare data


##  About the error "SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data".
You need to be administrator or site manager of the site "mysite" to be able to retrieve AuditShare data.


Regards.

**Comment by bforest** [comment]
I will fixed this error to return a valid JSON response (empty JSON object) but no, it's not possible to a SiteCollaborator or a SiteContributor to access AuditShare data.
If you want to do this, you need to modify the code: https://github.com/atolcd/alfresco-audit-share/blob/master/module_alfresco/src/main/java/com/atolcd/alfresco/helper/PermissionsHelper.java#L58

Regards.

**Comment by SandeepReddy496** [comment]
Hi sir,

Can you please fix this, for give the permissions to retrieve AuditShare data as per User Permissions.

**Comment by bforest** [comment]
Sorry but it's not an issue but an enhancement and I don't think we will do this.

Regards.

**Comment by SandeepReddy496** [comment]
Hi Sir,

i am imported this project into eclipse,

but i am facing following issue, please help me wait

[INFO] Scanning for projects...
[INFO] Downloading: http://oss.sonatype.org/content/groups/public/com/atolcd/alfresco/amp-maven-plugin/${alfresco-maven.version}/amp-maven-plugin-${alfresco-maven.version}.pom
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/atolcd/alfresco/amp-maven-plugin/${alfresco-maven.version}/amp-maven-plugin-${alfresco-maven.version}.pom
[INFO] Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/com/atolcd/alfresco/amp-maven-plugin/${alfresco-maven.version}/amp-maven-plugin-${alfresco-maven.version}.pom
[INFO] Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/com/atolcd/alfresco/amp-maven-plugin/${alfresco-maven.version}/amp-maven-plugin-${alfresco-maven.version}.pom
[INFO] Downloading: http://repo.maven.apache.org/maven2/com/atolcd/alfresco/amp-maven-plugin/${alfresco-maven.version}/amp-maven-plugin-${alfresco-maven.version}.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.alfresco.maven:auditshare-52X-repo:2.2.0 (F:\Projects\alfresco-audit-share-audit-share-52X-1.5.5\module_alfresco\pom.xml) has 3 errors
[ERROR]     Unresolveable build extension: Plugin com.atolcd.alfresco:amp-maven-plugin:${alfresco-maven.version} or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.atolcd.alfresco:amp-maven-plugin:jar:${alfresco-maven.version}: Could not transfer artifact com.atolcd.alfresco:amp-maven-plugin:pom:${alfresco-maven.version} from/to sonatype-public (http://oss.sonatype.org/content/groups/public): Illegal character in path at index 84: http://oss.sonatype.org/content/groups/public/com/atolcd/alfresco/amp-maven-plugin/${alfresco-maven.version}/amp-maven-plugin-${alfresco-maven.version}.pom -> [Help 2]
[ERROR]     Unknown packaging: amp @ line 17, column 14
[ERROR]     'build.plugins.plugin.version' for com.atolcd.alfresco:amp-maven-plugin must be a valid version but is '${alfresco-maven.version}'. @ line 64, column 18
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by SandeepReddy496** [comment]
Hi Sir,

I am facing this issue in Site Statistics (Site Dashboard) User role SiteCollaborator.

" You are not allowed to access this page 
you will redirect to the site dashboard"

I changed what ever you said, and deployed as AMP,  but still i am facing this problem.
Can you please help me out.

**Comment by bforest** [comment]
Hi,

You also need to modify code in Share module: https://github.com/atolcd/alfresco-audit-share/blob/4839a469cd2a7ba49d27c7c1461b7a278805c6d1/module_share/src/main/resources/templates/com/atolcd/statistics.js#L120

(https://github.com/search?utf8=%E2%9C%93&q=SiteManager+repo%3Aatolcd%2Falfresco-audit-share+path%3A%2Fmodule_share%2Fsrc%2Fmain&type=Code&ref=advsearch&l=&l=)

Regards.

**Comment by SandeepReddy496** [comment]
HI Sir,
I tried with following code for permissions, but it is showing error sir,
suggest me sir how to resolve it.

function checkPermissions() {
  // Check permissions
  if (page.url.templateArgs.site) {
    // We are in the context of a site, so call the repository to see if the user is site manager or not
	
	if(auditshare.isMemberOfGroups("SiteManager")){
	
	return auditshare.isSiteMangerOfAtLeastOneSite();
	}
    else if(auditshare.isMemberOfGroups("SiteCollaborator")){
	return auditshare.isSiteCollaboratorOfAtLeastOneSite();
	}
	else if(auditshare.isMemberOfGroups("SiteContributor")){
	   return auditshare.isSiteContributorOfAtLeastOneSite();
	   }
    return auditshare.isMemberOfGroups("SiteManager");
  } else if (user.isAdmin) {
    // User is an administrator
    return true;
  } 
  }

**Comment by SandeepReddy496** [comment]
Hi Sir,
Thank you so much For the Reply Sir,
If i want to show single site most read documents with usernames (I mean Hits with Hitting Usernames). In Which file i need to change the code ..?  can you please suggest me sir.
