### ISSUE TITLE
Read action not affected in alfresco using api

### ISSUE THREAD

**Issue by SandeepReddy496** [atolcd/alfresco-audit-share#22]
Hi,

I am retrieving documents from alfresco through API,  and I previewed the documents, But  READ , READCONTENT action not affected in site statistics.

Can you please help me .

**Comment by bforest** [comment]
Hi,

Only actions performed from Share UI are "audited" (see https://github.com/atolcd/alfresco-audit-share#using-the-module).

Regards.
