### ISSUE TITLE
Data is from module installation time only and not previous data

### ISSUE THREAD

**Issue by sumitt** [atolcd/alfresco-audit-share#24]
Hello,

I would like to first congratulate you for this great work. While my only concern is that I am able to see only the data which is uploaded after this module is installed in my instance. I am unable to see previous data which is uploaded before this module installation or from the creation of the instance.

Thanks for your kind support.

Sumit

**Comment by douglascrp** [comment]
I guess this is the expected result, as this module is responsible for generating and storing the information it uses for its "audit" functionality.
So, if it was not installed, there is no data to show.

**Comment by sumitt** [comment]
Thanks douglascrp for your response. My question was if module sync existing data first time while it installs. The challenge comes when we not install this module with the alfresco installation, we upload some data and some users loges in, later on whenever we install this module in alfresco user wants to see their all data and user statistics in the reports. Is there any way so that it picks up all the existing related data in first time of it's installation?

-Sumit

**Comment by bforest** [comment]
Hi,

@douglascrp is right, you can't.
Actions can be audited only when the audit-share module is installed.

Regards.
