### ISSUE TITLE
Deletions of folder which contains documents not decreased the Deletions count -  overall use Deletions

### ISSUE THREAD

**Issue by sumitt** [atolcd/alfresco-audit-share#26]
Hi,

If there are 100 documents in a folder and I delete the documents by deleting the folder. Then deletions count in overall use is not getting decreased for that site. While If I delete document by perform action on document only and not the folder then it works fine. If this is the bug can I request you for some idea about the change to fix it. I can work on this and submit the code.

Thanks for your kind support.

Sumit

**Comment by bforest** [comment]
Hi,

Yes it is a limitation of the module.
We can't know count the number of deleted items when deleting a folder.

Regards.
