### ISSUE TITLE
module_repo is not compiling with openjdk 11. 

### ISSUE THREAD

**Issue by monicakumari** [atolcd/alfresco-audit-share#29]
Hello, I want to deploy this on alfresco 6.2 but I am facing issue with compiling repo module. Getting the below error on 
> mvn clean install

my jdk version is 11. Please guide.

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.947 s
[INFO] Finished at: 2019-12-17T15:46:48+05:30
[INFO] Final Memory: 35M/370M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project auditshare-61X-repo: Fatal error compiling: invalid target release: 11 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Thanks.

**Comment by cshardey** [comment]
Got the same error during compilation

**Comment by jberthoux** [comment]
Hello,

Sorry for the delay. As you have probably seen in the sources, the module is now compatible with 6.2.x version of ACS. It should compile without issue with JDK 11. If it will not, we can re-open this issue.

Regards
