### ISSUE TITLE
Problem when install and uninstall AMP module

### ISSUE THREAD

**Issue by Lyn203** [atolcd/alfresco-audit-share#31]
+ When i change some code then force install AMP by MMT tool, it got notice about different version 1.5.9 and 1.5.10
+ When i uninstall AMP module by MMT tool, some file of this module keep exist int alfresco.war

**Comment by jberthoux** [comment]
Hi Lyn,

Do you have some logs file (alfresco.log) to share?

Regards,
Julien

**Comment by Lyn203** [comment]
OK i got it, first proplem cause error so just change version in pom.xml
The second problem did not cause the error so it's okay
