### ISSUE TITLE
Debugging module

### ISSUE THREAD

**Issue by Lyn203** [atolcd/alfresco-audit-share#32]
I'm so new when use Maven. Sir, I have a question, i can't use "mvndebug alfresco:run" like alfresco-amp archetype what i created from alfresco sdk, so how i configure it in pom.xml to integrate all necessary module for debugging this?

**Comment by jberthoux** [comment]
Hello Lyn,

I'm not sure what you want to debug. The Maven build or the developments of the module?

Regards,
Julien

**Comment by Lyn203** [comment]
Hello jberth,

When i want export data statistics using apache POI, i understand code logic, but it exported slightly imprecise data, so i need fix that small issue.

**Comment by jberthoux** [comment]
Hello Lyn,

So if I understand correctly you want to debug java code, right?

Regards,
Julien

**Comment by Lyn203** [comment]
Hello jberth,

Yeah, that's right. I want debug java code. So, have any way to debug it?

**Comment by jberthoux** [comment]
Hi Lyn,

If you want to debug Java code, you have to activate debug mode on the JVM: https://docs.alfresco.com/5.2/tasks/debug-installation.html
If you are using Eclipse as IDE, you can launch remote debug session: https://docs.alfresco.com/5.2/tasks/sdk-debug-eclipse.html

Regards,
Julien

**Comment by Lyn203** [comment]
Hi Julien,

Thank you for your reply. It 's so impressive, i got it.
