### ISSUE TITLE
Exception when suppressing referrer

### ISSUE THREAD

**Issue by cdwi** [atolcd/alfresco-audit-share#4]
I am using Firefox with RefControl add-on for better privacy.
When I try to comment on a discussion topic or blog post, the comment cannot be stored. In catalina.out I see a NullPointerException at ProxyAuditFilter.java:236: Obviously the code assumes that the referrer is always given.
(Of course, putting the Alfresco site on the whitelist of RefControl solves the issue, but the link between those points is not very obvious, so a better error message - or just ignoring those clicks then - would be helpful.)

**Comment by bforest** [comment]
Fixed
