### ISSUE TITLE
Alfresco 5.0 compatibility

### ISSUE THREAD

**Issue by cdwi** [atolcd/alfresco-audit-share#5]
The packages do not seem to be compatible with Alfresco 5.0.
Would be great to have the statistics also in the newest release ...

**Comment by mnesson** [comment]
Hi,

Is there a migration to Alfresco 5.2?
If so, when is it planned?

Thanks in advance,
cordially

**Comment by bforest** [comment]
Hi,

Alfresco 5.2 compatibilty upgrade is already done, we will publish sources shortly.

Regards.

**Comment by monicakumari** [comment]
Hello Bertrand,
This will be very helpful for us. I am waiting for the updated source. How much time will it take to update this add-on's code ?

Thank you.

**Comment by bforest** [comment]
Hi,

Sources have been updated.

master        => Alfresco 5.2.x
5.1.X branch => Alfresco 5.1.x
5.0.X branch => Alfresco 5.0.x
4.2.X branch => Alfresco 4.2.x

Regards.

**Comment by mnesson** [comment]
Thanks Bertrand!

Cordialement,
NESSON Melvin

2018-03-22 17:13 GMT+01:00 Bertrand FOREST <notifications@github.com>:

**Comment by monicakumari** [comment]
Thanks alot Bertrand.
